### ISSUE TITLE
Fix CI silent errors

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-subscriptions#21]
**Describe the bug**
@vickywane look through the CI and check for errors that should be stopping the CI run but are currently silently ignored.

[Here is an example](https://github.com/ambianic/ambianic-subscriptions/runs/2832953586#step:12:85).

```
An npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the NPM_TOKEN environment variable on your CI environment.

Please make sure to create an npm token (https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the NPM_TOKEN environment variable on your CI environment. The token must allow to publish to the registry https://registry.npmjs.org/.

AggregateError: 
    SemanticReleaseError: No npm token specified.
        at module.exports (/home/runner/work/ambianic-subscriptions/ambianic-subscriptions/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/home/runner/work/ambianic-subscriptions/ambianic-subscriptions/node_modules/@semantic-release/npm/lib/set-npmrc-auth.js:45:31)
        at module.exports (/home/runner/work/ambianic-subscriptions/ambianic-subscriptions/node_modules/@semantic-release/npm/lib/verify-auth.js:17:9)
```

**Comment by ivelin** [comment]
The CI build should not try to push an npm package. A release of this repo does not produce an npm package, just a standalone app for serverless functions. Similar to the ambianic-ui release. No npm package generated via semantic release.

**Comment by vickywane** [comment]
@ivelin As shown in the CI log, the CI build failed and other subsequent jobs (`Code Coverage Report` and `Checkout generated files`)were stopped at that point.

I have restricted semantic-release to only manage the versioning of this project.
